name: Flutter Web

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build web --web-renderer canvaskit
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Build and Push Release to DockerHub
      shell: bash
      run: ./build_and_push.sh
    - name: Deploy to CapRover
      uses: caprover/deploy-from-github@d76580d79952f6841c453bb3ed37ef452b19752c
      with:
          server: ${{ secrets.CAPROVER_SERVER }}
          app: ${{ env.APP_NAME }}
          token: '${{ secrets.APP_TOKEN }}'
          image: '${{ env.FULL_IMAGE_NAME }}'
            
    
      
   
    
