name: Flutter Web

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
          
    - name: Install dependencies
      run: flutter packages get
      
    - name: Build web
      run: flutter build web --web-renderer canvaskit
      
   
    - name: Deploy to CapRover
      uses: caprover/deploy-from-github@d76580d79952f6841c453bb3ed37ef452b19752c
      with:
          server: ${{ secrets.CAPROVER_SERVER }}
          app: ${{ env.APP_NAME }}
          token: '${{ secrets.APP_TOKEN }}'
          image: '${{ env.FULL_IMAGE_NAME }}'
